# Generated by Django 5.2.13 on 2026-05-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anesthesiologistprofile',
            old_name='edit_anesthesia_records',
            new_name='can_edit_anesthesia_records',
        ),
    ]
