# Generated by Django 5.2.13 on 2026-06-15 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_hrmanagerprofile_employee_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Optional holiday (not mandatory)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning (8 AM - 2 PM)'), ('EVENING', 'Evening (2 PM - 8 PM)'), ('NIGHT', 'Night (8 PM - 8 AM)'), ('ONCALL', 'On-Call (24 hours)'), ('CUSTOM', 'Custom')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_on_site', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes about this shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PENDING_SWAP', 'Pending Swap'), ('SWAPPED', 'Swapped'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('swap_status', models.CharField(blank=True, max_length=20, null=True)),
                ('swap_requested_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('attendance_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['END', 'GYN', 'ANE']}, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('swap_requested_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.shift')),
            ],
            options={
                'verbose_name': 'Doctor Shift Assignment',
                'verbose_name_plural': 'Doctor Shift Assignments',
                'ordering': ['shift_date', 'shift__start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], default='ABSENT', max_length=20)),
                ('late_minutes', models.IntegerField(default=0, help_text='Minutes late for the shift')),
                ('overtime_minutes', models.IntegerField(default=0, help_text='Minutes worked beyond shift end')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.doctorshiftassignment')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Attendance',
                'verbose_name_plural': 'Shift Attendances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_swaps', to=settings.AUTH_USER_MODEL)),
                ('requesting_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_request_from', to='hr.doctorshiftassignment')),
                ('requesting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swap_requests', to=settings.AUTH_USER_MODEL)),
                ('target_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_request_to', to='hr.doctorshiftassignment')),
                ('target_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swap_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Swap Request',
                'verbose_name_plural': 'Shift Swap Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for which balance applies')),
                ('annual_allocated', models.DecimalField(decimal_places=1, default=20, max_digits=5)),
                ('annual_used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('sick_allocated', models.DecimalField(decimal_places=1, default=12, max_digits=5)),
                ('sick_used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('casual_allocated', models.DecimalField(decimal_places=1, default=10, max_digits=5)),
                ('casual_used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('user', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='doctorshiftassignment',
            index=models.Index(fields=['shift_date', 'status'], name='hr_doctorsh_shift_d_bcd81c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorshiftassignment',
            index=models.Index(fields=['doctor', 'shift_date'], name='hr_doctorsh_doctor__2b8b14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorshiftassignment',
            unique_together={('doctor', 'shift_date', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftattendance',
            unique_together={('assignment', 'date')},
        ),
    ]
