# Generated by Django 5.2.13 on 2026-05-06 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, help_text='PT001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('treatment_type', models.CharField(blank=True, choices=[('IVF', 'In Vitro Fertilization(IVF)'), ('IUI', 'IntraUterine Insemination(IUI)'), ('FET', 'Frozen Embryo Transfer(FET)'), ('ICSI', 'IntraCytoplasmic Sperm Injection(ICSI)'), ('OI', 'Ovulation Induction'), ('IVM', 'In Vitro Maturation'), ('EGG_FREEZE', 'Egg Freezing'), ('EMBRYO_FREEZE', 'Egg Freezing'), ('SPERM_FREEZE', 'Sperm Freeze'), ('PGT', 'Preimplantation Genetic Testing(PGT)'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('ACT', 'Active Treatment'), ('HOL', 'On Hold'), ('COM', 'Completed'), ('CAN', 'Cancelled')], default='PEN', max_length=3)),
                ('years_of_infertility', models.PositiveIntegerField(blank=True, default=0)),
                ('previous_ivf_attempts', models.PositiveIntegerField(blank=True, default=0)),
                ('known_allergies', models.TextField(blank=True)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['GYN', 'END']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_of', to='patients.patientprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_on'],
            },
        ),
    ]
