# Generated by Django 5.2.13 on 2026-05-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientprofile_treatment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
