# Generated by Django 5.2.13 on 2026-06-19 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacistprofile_can_manage_inventory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medication Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(choices=[('IU', 'IU'), ('MG', 'mg'), ('MCG', 'mcg'), ('ML', 'ml'), ('G', 'g'), ('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('VIAL', 'Vial'), ('AMPOULE', 'Ampoule'), ('BOX', 'Box'), ('UNIT', 'Unit')], default='UNIT', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('minimum_stock', models.IntegerField(default=5)),
                ('maximum_stock', models.IntegerField(default=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('temperature_requirement', models.CharField(blank=True, max_length=50)),
                ('special_handling', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_controlled', models.BooleanField(default=False)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('requires_doctor_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('side_effects', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='pharmacy.medicationcategory')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='pharmacy.medicationmanufacturer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Add Stock'), ('REMOVE', 'Remove Stock'), ('SET', 'Set Quantity'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('RETURNED', 'Returned'), ('DISPENSED', 'Dispensed')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase Order'), ('DISPENSING', 'Dispensing to Patient'), ('RETURN', 'Return from Patient'), ('DAMAGE', 'Damaged Goods'), ('EXPIRY', 'Expired Stock'), ('INVENTORY', 'Inventory Count'), ('OTHER', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='pharmacy.medication')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('CRITICAL', 'Critical Stock'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pharmacy.medication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name'], name='pharmacy_me_name_46a660_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['category'], name='pharmacy_me_categor_e2528a_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['current_stock'], name='pharmacy_me_current_d63b94_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['expiry_date'], name='pharmacy_me_expiry__f658e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['medication'], name='pharmacy_st_medicat_717988_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['performed_at'], name='pharmacy_st_perform_766a08_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['medication'], name='pharmacy_st_medicat_4ec256_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type'], name='pharmacy_st_alert_t_f739b8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['status'], name='pharmacy_st_status_0d5c8a_idx'),
        ),
    ]
