# Generated by Django 5.2.13 on 2026-05-18 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_staffdepartmentassignment_notes'),
        ('patients', '0003_alter_patientprofile_treatment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_reason', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_CONSULT', 'In Consult'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['END', 'GYN', 'ANE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_tickets_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_tickets', to='departments.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_tickets', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['date', 'token_number'],
                'unique_together': {('date', 'token_number')},
            },
        ),
    ]
