# Generated by Django 5.2.13 on 2026-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticket',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_CONSULT', 'In Consult'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='opticket',
            name='visit_reason',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('LAB_COLLECTION', 'Lab Sample Collection'), ('SCAN', 'Scan/Ultrasound'), ('PROCEDURE', 'Procedure'), ('MEDICATION', 'Medication'), ('OTHER', 'Other')], default='WAITING', max_length=20),
        ),
    ]
