# Generated by Django 5.2.13 on 2026-05-20 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_opticket_status_alter_opticket_visit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
