# Generated by Django 5.2.13 on 2026-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_opticket_visit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticket',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opticket',
            name='visit_reason',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('LAB_COLLECTION', 'Lab Sample Collection'), ('SCAN', 'Scan/Ultrasound'), ('PROCEDURE', 'Procedure'), ('MEDICATION', 'Medication'), ('OTHER', 'Other')], default='CONSULTATION', max_length=50),
        ),
    ]
