# Generated by Django 5.2.13 on 2026-05-20 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_opticket_notes_alter_opticket_visit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 5, 20, 7, 2, 57, 269575, tzinfo=datetime.timezone.utc)),
        ),
    ]
