# Generated by Django 5.2.13 on 2026-05-20 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_opticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticket',
            name='date',
            field=models.DateField(default=datetime.date(2026, 5, 20)),
        ),
    ]
