# Generated by Django 5.2.13 on 2026-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_opticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticket',
            name='payment_done',
            field=models.BooleanField(default=True),
        ),
    ]
