# Generated by Django 5.2.13 on 2026-05-23 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_opticket_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
