# Generated by Django 5.2.13 on 2026-06-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_opticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticket',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opticket',
            name='qr_code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
