# Generated by Django 5.2.13 on 2026-06-03 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_opticket_qr_code_opticket_qr_code_generated_at'),
        ('departments', '0002_staffdepartmentassignment_notes'),
        ('patients', '0005_alter_patientprofile_assigned_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('token_number', models.PositiveIntegerField(blank=True, null=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('appointment_type', models.CharField(choices=[('REGULAR', 'Regular'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('WALK_IN', 'Walk-in'), ('TELEHEALTH', 'Telehealth')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('visit_reason', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('LAB_COLLECTION', 'Lab Sample Collection'), ('SCAN', 'Scan/Ultrasound'), ('PROCEDURE', 'Procedure'), ('MEDICATION', 'Medication'), ('OTHER', 'Other')], default='CONSULTATION', max_length=50)),
                ('symptoms', models.TextField(blank=True, help_text="Patient's symptoms or complaints")),
                ('notes', models.TextField(blank=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('rescheduled_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_type', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='departments.department')),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['END', 'GYN', 'ANE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date', 'appointment_time', 'token_number'],
                'indexes': [models.Index(fields=['appointment_date', 'doctor'], name='appointment_appoint_c5b3da_idx'), models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_8037cd_idx'), models.Index(fields=['status', 'appointment_date'], name='appointment_status_7c15d1_idx')],
            },
        ),
    ]
